### ISSUE TITLE
Question the section "Unsupervised Training"

### ISSUE THREAD

**Issue by 1132520084** [pondruska/DeepTracking#1]
I have read your paper "Deep Tracking: Seeing Beyond Seeing Using Recurrent Neural Networks". but I don't understand the approach called “unsupervised training”. In the section “Unsupervised Training”, you said "we propose to train the network not to predict **the current state** , but a **state in the future**" , can you tell me the difference between them ? Thank you.
And is the Equation 7 used in the unsupervised training ?
Thank you.

**Comment by pondruska** [comment]
The difference is small but important. The intuition goes as follows: during training we provide the network a sensor input **x** up to some point _t_ and then instead of trying to directly predict desired output **y** at time _t_ we make the network to imagine the expected output a few timesteps later at time _t+n_ (i.e. we make the network to imagine the expected _future_). It turns out that when the network gets good at this _"imagination task"_ it performs well with tracking the objects in occlusions as both of these tasks require learned _"imagination capability"_.

Equation 7 is used during the unsupervised training as well but with a slight modification that we penalise the network based on how good it is at imagining the visible part of future output. The following 2 pictures showing the difference should help:

![supervised training](https://cloud.githubusercontent.com/assets/9326502/13491896/f0ce8a84-e12c-11e5-892f-1fee4ae5bf61.png)

![unsupervised training](https://cloud.githubusercontent.com/assets/9326502/13491919/10d3dc58-e12d-11e5-9ee2-dffdd7e634e4.png)

Is this more clear?

**Comment by ypxie** [comment]
Thanks for the explanation, but it seems to me that the network should learn to predict the future input x_{t+n} rather than the binary mask y_{t+n}. Why does it work? There seems  no such supervision at all.
